INSERT INTO aliases (name, aliasable_id, aliasable_type, created_at, updated_at) VALUES ('Heart Attack',280,'drg',now(),now());
INSERT INTO aliases (name, aliasable_id, aliasable_type, created_at, updated_at) VALUES ('Heart Attack',281,'drg',now(),now());
INSERT INTO aliases (name, aliasable_id, aliasable_type, created_at, updated_at) VALUES ('Heart Attack',282,'drg',now(),now());
INSERT INTO aliases (name, aliasable_id, aliasable_type, created_at, updated_at) VALUES ('Heart Failure',291,'drg',now(),now());
INSERT INTO aliases (name, aliasable_id, aliasable_type, created_at, updated_at) VALUES ('Heart Failure',292,'drg',now(),now());
INSERT INTO aliases (name, aliasable_id, aliasable_type, created_at, updated_at) VALUES ('Heart Failure',293,'drg',now(),now());
INSERT INTO aliases (name, aliasable_id, aliasable_type, created_at, updated_at) VALUES ('Chronic Lung Disease',190,'drg',now(),now());
INSERT INTO aliases (name, aliasable_id, aliasable_type, created_at, updated_at) VALUES ('Chronic Lung Disease',191,'drg',now(),now());
INSERT INTO aliases (name, aliasable_id, aliasable_type, created_at, updated_at) VALUES ('Chronic Lung Disease',192,'drg',now(),now());
INSERT INTO aliases (name, aliasable_id, aliasable_type, created_at, updated_at) VALUES ('Pneumonia',193,'drg',now(),now());
INSERT INTO aliases (name, aliasable_id, aliasable_type, created_at, updated_at) VALUES ('Diabetes',637,'drg',now(),now());
INSERT INTO aliases (name, aliasable_id, aliasable_type, created_at, updated_at) VALUES ('Chest Pain',313,'drg',now(),now());
INSERT INTO aliases (name, aliasable_id, aliasable_type, created_at, updated_at) VALUES ('Heart & Blood Vessels - Heart Valve',219,'drg',now(),now());
INSERT INTO aliases (name, aliasable_id, aliasable_type, created_at, updated_at) VALUES ('Heart & Blood Vessels - Heart Valve',220,'drg',now(),now());
INSERT INTO aliases (name, aliasable_id, aliasable_type, created_at, updated_at) VALUES ('Heart & Blood Vessels - Heart Valve',221,'drg',now(),now());
INSERT INTO aliases (name, aliasable_id, aliasable_type, created_at, updated_at) VALUES ('Heart & Blood Vessels - Major Heart & Blood Vessels',237,'drg',now(),now());
INSERT INTO aliases (name, aliasable_id, aliasable_type, created_at, updated_at) VALUES ('Heart & Blood Vessels - Defibrillator Implant - no Cardiac Catheterization',226,'drg',now(),now());
INSERT INTO aliases (name, aliasable_id, aliasable_type, created_at, updated_at) VALUES ('Heart & Blood Vessels - Defibrillator Implant - no Cardiac Catheterization',227,'drg',now(),now());
INSERT INTO aliases (name, aliasable_id, aliasable_type, created_at, updated_at) VALUES ('Heart & Blood Vessels - Defibrillator Implant - with Cardiac Catheterization',224,'drg',now(),now());
INSERT INTO aliases (name, aliasable_id, aliasable_type, created_at, updated_at) VALUES ('Heart & Blood Vessels - Defibrillator Implant - with Cardiac Catheterization',225,'drg',now(),now());
INSERT INTO aliases (name, aliasable_id, aliasable_type, created_at, updated_at) VALUES ('Heart & Blood Vessels - Head & Neck Blood Vessels',38,'drg',now(),now());
INSERT INTO aliases (name, aliasable_id, aliasable_type, created_at, updated_at) VALUES ('Heart & Blood Vessels - Head & Neck Blood Vessels',39,'drg',now(),now());
INSERT INTO aliases (name, aliasable_id, aliasable_type, created_at, updated_at) VALUES ('Heart & Blood Vessels - Heart Bypass',235,'drg',now(),now());
INSERT INTO aliases (name, aliasable_id, aliasable_type, created_at, updated_at) VALUES ('Heart & Blood Vessels - Heart Bypass',236,'drg',now(),now());
INSERT INTO aliases (name, aliasable_id, aliasable_type, created_at, updated_at) VALUES ('Heart & Blood Vessels - Pacemaker',243,'drg',now(),now());
INSERT INTO aliases (name, aliasable_id, aliasable_type, created_at, updated_at) VALUES ('Heart & Blood Vessels - Pacemaker',244,'drg',now(),now());
INSERT INTO aliases (name, aliasable_id, aliasable_type, created_at, updated_at) VALUES ('Heart & Blood Vessels - Angioplasties',247,'drg',now(),now());
INSERT INTO aliases (name, aliasable_id, aliasable_type, created_at, updated_at) VALUES ('Abdominal - Gallbladder (Laparoscopic)',417,'drg',now(),now());
INSERT INTO aliases (name, aliasable_id, aliasable_type, created_at, updated_at) VALUES ('Abdominal - Gallbladder (Laparoscopic)',418,'drg',now(),now());
INSERT INTO aliases (name, aliasable_id, aliasable_type, created_at, updated_at) VALUES ('Abdominal - Gallbladder (Laparoscopic)',419,'drg',now(),now());
INSERT INTO aliases (name, aliasable_id, aliasable_type, created_at, updated_at) VALUES ('Abdominal - Gallbladder (Non-Laparoscopic)',414,'drg',now(),now());
INSERT INTO aliases (name, aliasable_id, aliasable_type, created_at, updated_at) VALUES ('Abdominal - Hernia',353,'drg',now(),now());
INSERT INTO aliases (name, aliasable_id, aliasable_type, created_at, updated_at) VALUES ('Abdominal - Hernia',354,'drg',now(),now());
INSERT INTO aliases (name, aliasable_id, aliasable_type, created_at, updated_at) VALUES ('Abdominal - Hernia',355,'drg',now(),now());
INSERT INTO aliases (name, aliasable_id, aliasable_type, created_at, updated_at) VALUES ('Abdominal - Bowel',329,'drg',now(),now());
INSERT INTO aliases (name, aliasable_id, aliasable_type, created_at, updated_at) VALUES ('Abdominal - Bowel',330,'drg',now(),now());
INSERT INTO aliases (name, aliasable_id, aliasable_type, created_at, updated_at) VALUES ('Abdominal - Bowel',331,'drg',now(),now());
INSERT INTO aliases (name, aliasable_id, aliasable_type, created_at, updated_at) VALUES ('Abdominal - Stomach, Esophagus, Small Blowel',328,'drg',now(),now());
INSERT INTO aliases (name, aliasable_id, aliasable_type, created_at, updated_at) VALUES ('Neck, Back, Arms & Legs - Cervical Spine Fusion',471,'drg',now(),now());
INSERT INTO aliases (name, aliasable_id, aliasable_type, created_at, updated_at) VALUES ('Neck, Back, Arms & Legs - Cervical Spine Fusion',472,'drg',now(),now());
INSERT INTO aliases (name, aliasable_id, aliasable_type, created_at, updated_at) VALUES ('Neck, Back, Arms & Legs - Cervical Spine Fusion',473,'drg',now(),now());
INSERT INTO aliases (name, aliasable_id, aliasable_type, created_at, updated_at) VALUES ('Neck, Back, Arms & Legs - Other Spine Fusion',459,'drg',now(),now());
INSERT INTO aliases (name, aliasable_id, aliasable_type, created_at, updated_at) VALUES ('Neck, Back, Arms & Legs - Other Spine Fusion',460,'drg',now(),now());
INSERT INTO aliases (name, aliasable_id, aliasable_type, created_at, updated_at) VALUES ('Neck, Back, Arms & Legs - Back & Neck (no fusion)',490,'drg',now(),now());
INSERT INTO aliases (name, aliasable_id, aliasable_type, created_at, updated_at) VALUES ('Neck, Back, Arms & Legs - Back & Neck (no fusion)',491,'drg',now(),now());
INSERT INTO aliases (name, aliasable_id, aliasable_type, created_at, updated_at) VALUES ('Neck, Back, Arms & Legs - Arm & Shoulder',507,'drg',now(),now());
INSERT INTO aliases (name, aliasable_id, aliasable_type, created_at, updated_at) VALUES ('Neck, Back, Arms & Legs - Arm & Shoulder',508,'drg',now(),now());
INSERT INTO aliases (name, aliasable_id, aliasable_type, created_at, updated_at) VALUES ('Neck, Back, Arms & Legs - Multiple Joint (hip, knee, ankle)',461,'drg',now(),now());
INSERT INTO aliases (name, aliasable_id, aliasable_type, created_at, updated_at) VALUES ('Neck, Back, Arms & Legs - Multiple Joint (hip, knee, ankle)',462,'drg',now(),now());
INSERT INTO aliases (name, aliasable_id, aliasable_type, created_at, updated_at) VALUES ('Neck, Back, Arms & Legs - Joint Replacement/Reattachment (e.g., hip, knee)',469,'drg',now(),now());
INSERT INTO aliases (name, aliasable_id, aliasable_type, created_at, updated_at) VALUES ('Neck, Back, Arms & Legs - Joint Replacement/Reattachment (e.g., hip, knee)',470,'drg',now(),now());
INSERT INTO aliases (name, aliasable_id, aliasable_type, created_at, updated_at) VALUES ('Neck, Back, Arms & Legs - Joint Revision Surgery (hip, knee)',466,'drg',now(),now());
INSERT INTO aliases (name, aliasable_id, aliasable_type, created_at, updated_at) VALUES ('Neck, Back, Arms & Legs - Joint Revision Surgery (hip, knee)',467,'drg',now(),now());
INSERT INTO aliases (name, aliasable_id, aliasable_type, created_at, updated_at) VALUES ('Neck, Back, Arms & Legs - Joint Revision Surgery (hip, knee)',468,'drg',now(),now());
INSERT INTO aliases (name, aliasable_id, aliasable_type, created_at, updated_at) VALUES ('Neck, Back, Arms & Legs - Muscle & Bone Biopsy',477,'drg',now(),now());
INSERT INTO aliases (name, aliasable_id, aliasable_type, created_at, updated_at) VALUES ('Neck, Back, Arms & Legs - Muscle & Bone Biopsy',478,'drg',now(),now());
INSERT INTO aliases (name, aliasable_id, aliasable_type, created_at, updated_at) VALUES ('Neck, Back, Arms & Legs - Muscle & Bone Biopsy',479,'drg',now(),now());
INSERT INTO aliases (name, aliasable_id, aliasable_type, created_at, updated_at) VALUES ('Neck, Back, Arms & Legs - Other Bone & Muscle',515,'drg',now(),now());
INSERT INTO aliases (name, aliasable_id, aliasable_type, created_at, updated_at) VALUES ('Bladder, Kidney & Prostate - Kidney & Ureter For Cancer',656,'drg',now(),now());
INSERT INTO aliases (name, aliasable_id, aliasable_type, created_at, updated_at) VALUES ('Bladder, Kidney & Prostate - Kidney & Ureter For Cancer',657,'drg',now(),now());
INSERT INTO aliases (name, aliasable_id, aliasable_type, created_at, updated_at) VALUES ('Bladder, Kidney & Prostate - Kidney & Ureter For Cancer',658,'drg',now(),now());
INSERT INTO aliases (name, aliasable_id, aliasable_type, created_at, updated_at) VALUES ('Bladder, Kidney & Prostate - Kidney & Ureter Not For Cancer',659,'drg',now(),now());
INSERT INTO aliases (name, aliasable_id, aliasable_type, created_at, updated_at) VALUES ('Bladder, Kidney & Prostate - Kidney & Urinary Tract through Urethra',668,'drg',now(),now());
INSERT INTO aliases (name, aliasable_id, aliasable_type, created_at, updated_at) VALUES ('Bladder, Kidney & Prostate - Other Kidney & Urinary Tract',673,'drg',now(),now());
INSERT INTO aliases (name, aliasable_id, aliasable_type, created_at, updated_at) VALUES ('Bladder, Kidney & Prostate - Other Kidney & Urinary Tract',674,'drg',now(),now());
INSERT INTO aliases (name, aliasable_id, aliasable_type, created_at, updated_at) VALUES ('Bladder, Kidney & Prostate - Other Kidney & Urinary Tract',675,'drg',now(),now());
INSERT INTO aliases (name, aliasable_id, aliasable_type, created_at, updated_at) VALUES ('Bladder, Kidney & Prostate - Prostate',713,'drg',now(),now());
INSERT INTO aliases (name, aliasable_id, aliasable_type, created_at, updated_at) VALUES ('Bladder, Kidney & Prostate - Prostate',714,'drg',now(),now());
INSERT INTO aliases (name, aliasable_id, aliasable_type, created_at, updated_at) VALUES ('Female Reproductive - Female Reconstructive',748,'drg',now(),now());
INSERT INTO aliases (name, aliasable_id, aliasable_type, created_at, updated_at) VALUES ('Female Reproductive - Other Female Reproductive',743,'drg',now(),now());