class PopulateStatesTable < ActiveRecord::Migration
  def up
execute 'INSERT into states (name,abbrev) values ("ALABAMA","AL")'
execute 'INSERT into states (name,abbrev) values ("ALASKA","AK")'
execute 'INSERT into states (name,abbrev) values ("ARIZONA","AZ")'
execute 'INSERT into states (name,abbrev) values ("ARKANSAS","AR")'
execute 'INSERT into states (name,abbrev) values ("CALIFORNIA","CA")'
execute 'INSERT into states (name,abbrev) values ("COLORADO","CO")'
execute 'INSERT into states (name,abbrev) values ("CONNECTICUT","CT")'
execute 'INSERT into states (name,abbrev) values ("DELAWARE","DE")'
execute 'INSERT into states (name,abbrev) values ("FLORIDA","FL")'
execute 'INSERT into states (name,abbrev) values ("GEORGIA","GA")'
execute 'INSERT into states (name,abbrev) values ("HAWAII","HI")'
execute 'INSERT into states (name,abbrev) values ("IDAHO","ID")'
execute 'INSERT into states (name,abbrev) values ("ILLINOIS","IL")'
execute 'INSERT into states (name,abbrev) values ("INDIANA","IN")'
execute 'INSERT into states (name,abbrev) values ("IOWA","IA")'
execute 'INSERT into states (name,abbrev) values ("KANSAS","KS")'
execute 'INSERT into states (name,abbrev) values ("KENTUCKY","KY")'
execute 'INSERT into states (name,abbrev) values ("LOUISIANA","LA")'
execute 'INSERT into states (name,abbrev) values ("MAINE","ME")'
execute 'INSERT into states (name,abbrev) values ("MARYLAND","MD")'
execute 'INSERT into states (name,abbrev) values ("MASSACHUSETTS","MA")'
execute 'INSERT into states (name,abbrev) values ("MICHIGAN","MI")'
execute 'INSERT into states (name,abbrev) values ("MINNESOTA","MN")'
execute 'INSERT into states (name,abbrev) values ("MISSISSIPPI","MS")'
execute 'INSERT into states (name,abbrev) values ("MISSOURI","MO")'
execute 'INSERT into states (name,abbrev) values ("MONTANA","MT")'
execute 'INSERT into states (name,abbrev) values ("NEBRASKA","NE")'
execute 'INSERT into states (name,abbrev) values ("NEVADA","NV")'
execute 'INSERT into states (name,abbrev) values ("NEW HAMPSHIRE","NH")'
execute 'INSERT into states (name,abbrev) values ("NEW JERSEY","NJ")'
execute 'INSERT into states (name,abbrev) values ("NEW MEXICO","NM")'
execute 'INSERT into states (name,abbrev) values ("NEW YORK","NY")'
execute 'INSERT into states (name,abbrev) values ("NORTH CAROLINA","NC")'
execute 'INSERT into states (name,abbrev) values ("NORTH DAKOTA","ND")'
execute 'INSERT into states (name,abbrev) values ("OHIO","OH")'
execute 'INSERT into states (name,abbrev) values ("OKLAHOMA","OK")'
execute 'INSERT into states (name,abbrev) values ("OREGON","OR")'
execute 'INSERT into states (name,abbrev) values ("PENNSYLVANIA","PA")'
execute 'INSERT into states (name,abbrev) values ("RHODE ISLAND","RI")'
execute 'INSERT into states (name,abbrev) values ("SOUTH CAROLINA","SC")'
execute 'INSERT into states (name,abbrev) values ("SOUTH DAKOTA","SD")'
execute 'INSERT into states (name,abbrev) values ("TENNESSEE","TN")'
execute 'INSERT into states (name,abbrev) values ("TEXAS","TX")'
execute 'INSERT into states (name,abbrev) values ("UTAH","UT")'
execute 'INSERT into states (name,abbrev) values ("VERMONT","VT")'
execute 'INSERT into states (name,abbrev) values ("VIRGINIA","VA")'
execute 'INSERT into states (name,abbrev) values ("WASHINGTON","WA")'
execute 'INSERT into states (name,abbrev) values ("WEST VIRGINIA","WV")'
execute 'INSERT into states (name,abbrev) values ("WISCONSIN","WI")'
execute 'INSERT into states (name,abbrev) values ("WYOMING","WY")'

  end

  def down
  end
end
