class AddApcAverages < ActiveRecord::Migration
  def up

execute 'UPDATE apcs SET avg_estimated_submitted_charges = (select avg(average_estimated_submitted_charges) from apc_costs where apc_code = 12), avg_total_payments = (select avg(average_total_payments) from apc_costs where apc_code = 12) where code = 12'
execute 'UPDATE apcs SET avg_estimated_submitted_charges = (select avg(average_estimated_submitted_charges) from apc_costs where apc_code = 13), avg_total_payments = (select avg(average_total_payments) from apc_costs where apc_code = 13) where code = 13'
execute 'UPDATE apcs SET avg_estimated_submitted_charges = (select avg(average_estimated_submitted_charges) from apc_costs where apc_code = 15), avg_total_payments = (select avg(average_total_payments) from apc_costs where apc_code = 15) where code = 15'
execute 'UPDATE apcs SET avg_estimated_submitted_charges = (select avg(average_estimated_submitted_charges) from apc_costs where apc_code = 19), avg_total_payments = (select avg(average_total_payments) from apc_costs where apc_code = 19) where code = 19'
execute 'UPDATE apcs SET avg_estimated_submitted_charges = (select avg(average_estimated_submitted_charges) from apc_costs where apc_code = 20), avg_total_payments = (select avg(average_total_payments) from apc_costs where apc_code = 20) where code = 20'
execute 'UPDATE apcs SET avg_estimated_submitted_charges = (select avg(average_estimated_submitted_charges) from apc_costs where apc_code = 73), avg_total_payments = (select avg(average_total_payments) from apc_costs where apc_code = 73) where code = 73'
execute 'UPDATE apcs SET avg_estimated_submitted_charges = (select avg(average_estimated_submitted_charges) from apc_costs where apc_code = 74), avg_total_payments = (select avg(average_total_payments) from apc_costs where apc_code = 74) where code = 74'
execute 'UPDATE apcs SET avg_estimated_submitted_charges = (select avg(average_estimated_submitted_charges) from apc_costs where apc_code = 78), avg_total_payments = (select avg(average_total_payments) from apc_costs where apc_code = 78) where code = 78'
execute 'UPDATE apcs SET avg_estimated_submitted_charges = (select avg(average_estimated_submitted_charges) from apc_costs where apc_code = 96), avg_total_payments = (select avg(average_total_payments) from apc_costs where apc_code = 96) where code = 96'
execute 'UPDATE apcs SET avg_estimated_submitted_charges = (select avg(average_estimated_submitted_charges) from apc_costs where apc_code = 203), avg_total_payments = (select avg(average_total_payments) from apc_costs where apc_code = 203) where code = 203'
execute 'UPDATE apcs SET avg_estimated_submitted_charges = (select avg(average_estimated_submitted_charges) from apc_costs where apc_code = 204), avg_total_payments = (select avg(average_total_payments) from apc_costs where apc_code = 204) where code = 204'
execute 'UPDATE apcs SET avg_estimated_submitted_charges = (select avg(average_estimated_submitted_charges) from apc_costs where apc_code = 206), avg_total_payments = (select avg(average_total_payments) from apc_costs where apc_code = 206) where code = 206'
execute 'UPDATE apcs SET avg_estimated_submitted_charges = (select avg(average_estimated_submitted_charges) from apc_costs where apc_code = 207), avg_total_payments = (select avg(average_total_payments) from apc_costs where apc_code = 207) where code = 207'
execute 'UPDATE apcs SET avg_estimated_submitted_charges = (select avg(average_estimated_submitted_charges) from apc_costs where apc_code = 209), avg_total_payments = (select avg(average_total_payments) from apc_costs where apc_code = 209) where code = 209'
execute 'UPDATE apcs SET avg_estimated_submitted_charges = (select avg(average_estimated_submitted_charges) from apc_costs where apc_code = 265), avg_total_payments = (select avg(average_total_payments) from apc_costs where apc_code = 265) where code = 265'
execute 'UPDATE apcs SET avg_estimated_submitted_charges = (select avg(average_estimated_submitted_charges) from apc_costs where apc_code = 267), avg_total_payments = (select avg(average_total_payments) from apc_costs where apc_code = 267) where code = 267'
execute 'UPDATE apcs SET avg_estimated_submitted_charges = (select avg(average_estimated_submitted_charges) from apc_costs where apc_code = 269), avg_total_payments = (select avg(average_total_payments) from apc_costs where apc_code = 269) where code = 269'
execute 'UPDATE apcs SET avg_estimated_submitted_charges = (select avg(average_estimated_submitted_charges) from apc_costs where apc_code = 270), avg_total_payments = (select avg(average_total_payments) from apc_costs where apc_code = 270) where code = 270'
execute 'UPDATE apcs SET avg_estimated_submitted_charges = (select avg(average_estimated_submitted_charges) from apc_costs where apc_code = 336), avg_total_payments = (select avg(average_total_payments) from apc_costs where apc_code = 336) where code = 336'
execute 'UPDATE apcs SET avg_estimated_submitted_charges = (select avg(average_estimated_submitted_charges) from apc_costs where apc_code = 368), avg_total_payments = (select avg(average_total_payments) from apc_costs where apc_code = 368) where code = 368'
execute 'UPDATE apcs SET avg_estimated_submitted_charges = (select avg(average_estimated_submitted_charges) from apc_costs where apc_code = 369), avg_total_payments = (select avg(average_total_payments) from apc_costs where apc_code = 369) where code = 369'
execute 'UPDATE apcs SET avg_estimated_submitted_charges = (select avg(average_estimated_submitted_charges) from apc_costs where apc_code = 377), avg_total_payments = (select avg(average_total_payments) from apc_costs where apc_code = 377) where code = 377'
execute 'UPDATE apcs SET avg_estimated_submitted_charges = (select avg(average_estimated_submitted_charges) from apc_costs where apc_code = 604), avg_total_payments = (select avg(average_total_payments) from apc_costs where apc_code = 604) where code = 604'
execute 'UPDATE apcs SET avg_estimated_submitted_charges = (select avg(average_estimated_submitted_charges) from apc_costs where apc_code = 605), avg_total_payments = (select avg(average_total_payments) from apc_costs where apc_code = 605) where code = 605'
execute 'UPDATE apcs SET avg_estimated_submitted_charges = (select avg(average_estimated_submitted_charges) from apc_costs where apc_code = 606), avg_total_payments = (select avg(average_total_payments) from apc_costs where apc_code = 606) where code = 606'
execute 'UPDATE apcs SET avg_estimated_submitted_charges = (select avg(average_estimated_submitted_charges) from apc_costs where apc_code = 607), avg_total_payments = (select avg(average_total_payments) from apc_costs where apc_code = 607) where code = 607'
execute 'UPDATE apcs SET avg_estimated_submitted_charges = (select avg(average_estimated_submitted_charges) from apc_costs where apc_code = 608), avg_total_payments = (select avg(average_total_payments) from apc_costs where apc_code = 608) where code = 608'
execute 'UPDATE apcs SET avg_estimated_submitted_charges = (select avg(average_estimated_submitted_charges) from apc_costs where apc_code = 690), avg_total_payments = (select avg(average_total_payments) from apc_costs where apc_code = 690) where code = 690'
execute 'UPDATE apcs SET avg_estimated_submitted_charges = (select avg(average_estimated_submitted_charges) from apc_costs where apc_code = 692), avg_total_payments = (select avg(average_total_payments) from apc_costs where apc_code = 692) where code = 692'
execute 'UPDATE apcs SET avg_estimated_submitted_charges = (select avg(average_estimated_submitted_charges) from apc_costs where apc_code = 698), avg_total_payments = (select avg(average_total_payments) from apc_costs where apc_code = 698) where code = 698'
  end

  def down
  end
end
