class FixPrimaryAddSpecialty < ActiveRecord::Migration
  def up
  	remove_column :specialties, :primary
  	add_column :providers_specialties, :primary, :boolean

execute 'INSERT INTO specialties (id, name, created_at, updated_at) VALUES (128,"",now(),now())'
execute 'INSERT INTO specialties (id, name, created_at, updated_at) VALUES (69,"ADDICTION MEDICINE",now(),now())'
execute 'INSERT INTO specialties (id, name, created_at, updated_at) VALUES (17,"ALLERGY/IMMUNOLOGY",now(),now())'
execute 'INSERT INTO specialties (id, name, created_at, updated_at) VALUES (15,"ANESTHESIOLOGY",now(),now())'
execute 'INSERT INTO specialties (id, name, created_at, updated_at) VALUES (51,"ANESTHESIOLOGY ASSISTANT",now(),now())'
execute 'INSERT INTO specialties (id, name, created_at, updated_at) VALUES (27,"AUDIOLOGIST",now(),now())'
execute 'INSERT INTO specialties (id, name, created_at, updated_at) VALUES (39,"CARDIAC ELECTROPHYSIOLOGY",now(),now())'
execute 'INSERT INTO specialties (id, name, created_at, updated_at) VALUES (24,"CARDIAC SURGERY",now(),now())'
execute 'INSERT INTO specialties (id, name, created_at, updated_at) VALUES (18,"CARDIOVASCULAR DISEASE (CARDIOLOGY)",now(),now())'
execute 'INSERT INTO specialties (id, name, created_at, updated_at) VALUES (50,"CERTIFIED NURSE MIDWIFE",now(),now())'
execute 'INSERT INTO specialties (id, name, created_at, updated_at) VALUES (20,"CERTIFIED REGISTERED NURSE ANESTHETIST",now(),now())'
execute 'INSERT INTO specialties (id, name, created_at, updated_at) VALUES (5,"CHIROPRACTIC",now(),now())'
execute 'INSERT INTO specialties (id, name, created_at, updated_at) VALUES (48,"CLINICAL NURSE SPECIALIST",now(),now())'
execute 'INSERT INTO specialties (id, name, created_at, updated_at) VALUES (11,"CLINICAL PSYCHOLOGIST",now(),now())'
execute 'INSERT INTO specialties (id, name, created_at, updated_at) VALUES (1,"CLINICAL SOCIAL WORKER",now(),now())'
execute 'INSERT INTO specialties (id, name, created_at, updated_at) VALUES (8,"COLORECTAL SURGERY (PROCTOLOGY)",now(),now())'
execute 'INSERT INTO specialties (id, name, created_at, updated_at) VALUES (63,"CRITICAL CARE (INTENSIVISTS)",now(),now())'
execute 'INSERT INTO specialties (id, name, created_at, updated_at) VALUES (26,"DERMATOLOGY",now(),now())'
execute 'INSERT INTO specialties (id, name, created_at, updated_at) VALUES (4,"DIAGNOSTIC RADIOLOGY",now(),now())'
execute 'INSERT INTO specialties (id, name, created_at, updated_at) VALUES (33,"EMERGENCY MEDICINE",now(),now())'
execute 'INSERT INTO specialties (id, name, created_at, updated_at) VALUES (41,"ENDOCRINOLOGY",now(),now())'
execute 'INSERT INTO specialties (id, name, created_at, updated_at) VALUES (6,"FAMILY PRACTICE",now(),now())'
execute 'INSERT INTO specialties (id, name, created_at, updated_at) VALUES (36,"GASTROENTEROLOGY",now(),now())'
execute 'INSERT INTO specialties (id, name, created_at, updated_at) VALUES (38,"GENERAL PRACTICE",now(),now())'
execute 'INSERT INTO specialties (id, name, created_at, updated_at) VALUES (40,"GENERAL SURGERY",now(),now())'
execute 'INSERT INTO specialties (id, name, created_at, updated_at) VALUES (44,"GERIATRIC MEDICINE",now(),now())'
execute 'INSERT INTO specialties (id, name, created_at, updated_at) VALUES (55,"GERIATRIC PSYCHIATRY",now(),now())'
execute 'INSERT INTO specialties (id, name, created_at, updated_at) VALUES (65,"GYNECOLOGICAL ONCOLOGY",now(),now())'
execute 'INSERT INTO specialties (id, name, created_at, updated_at) VALUES (28,"HAND SURGERY",now(),now())'
execute 'INSERT INTO specialties (id, name, created_at, updated_at) VALUES (71,"HEMATOLOGY",now(),now())'
execute 'INSERT INTO specialties (id, name, created_at, updated_at) VALUES (54,"HEMATOLOGY/ONCOLOGY",now(),now())'
execute 'INSERT INTO specialties (id, name, created_at, updated_at) VALUES (52,"HOSPICE/PALLIATIVE CARE",now(),now())'
execute 'INSERT INTO specialties (id, name, created_at, updated_at) VALUES (45,"INFECTIOUS DISEASE",now(),now())'
execute 'INSERT INTO specialties (id, name, created_at, updated_at) VALUES (10,"INTERNAL MEDICINE",now(),now())'
execute 'INSERT INTO specialties (id, name, created_at, updated_at) VALUES (31,"INTERVENTIONAL PAIN MANAGEMENT",now(),now())'
execute 'INSERT INTO specialties (id, name, created_at, updated_at) VALUES (61,"INTERVENTIONAL RADIOLOGY",now(),now())'
execute 'INSERT INTO specialties (id, name, created_at, updated_at) VALUES (77,"MASS IMMUNIZATION ROSTER BILLER",now(),now())'
execute 'INSERT INTO specialties (id, name, created_at, updated_at) VALUES (59,"MAXILLOFACIAL SURGERY",now(),now())'
execute 'INSERT INTO specialties (id, name, created_at, updated_at) VALUES (37,"MEDICAL ONCOLOGY",now(),now())'
execute 'INSERT INTO specialties (id, name, created_at, updated_at) VALUES (46,"NEPHROLOGY",now(),now())'
execute 'INSERT INTO specialties (id, name, created_at, updated_at) VALUES (25,"NEUROLOGY",now(),now())'
execute 'INSERT INTO specialties (id, name, created_at, updated_at) VALUES (73,"NEUROPSYCHIATRY",now(),now())'
execute 'INSERT INTO specialties (id, name, created_at, updated_at) VALUES (47,"NEUROSURGERY",now(),now())'
execute 'INSERT INTO specialties (id, name, created_at, updated_at) VALUES (66,"NUCLEAR MEDICINE",now(),now())'
execute 'INSERT INTO specialties (id, name, created_at, updated_at) VALUES (12,"NURSE PRACTITIONER",now(),now())'
execute 'INSERT INTO specialties (id, name, created_at, updated_at) VALUES (16,"OBSTETRICS/GYNECOLOGY",now(),now())'
execute 'INSERT INTO specialties (id, name, created_at, updated_at) VALUES (34,"OCCUPATIONAL THERAPIST",now(),now())'
execute 'INSERT INTO specialties (id, name, created_at, updated_at) VALUES (9,"OPHTHALMOLOGY",now(),now())'
execute 'INSERT INTO specialties (id, name, created_at, updated_at) VALUES (2,"OPTOMETRY",now(),now())'
execute 'INSERT INTO specialties (id, name, created_at, updated_at) VALUES (42,"ORAL SURGERY (DENTIST ONLY)",now(),now())'
execute 'INSERT INTO specialties (id, name, created_at, updated_at) VALUES (22,"ORTHOPEDIC SURGERY",now(),now())'
execute 'INSERT INTO specialties (id, name, created_at, updated_at) VALUES (56,"OSTEOPATHIC MANIPULATIVE MEDICINE",now(),now())'
execute 'INSERT INTO specialties (id, name, created_at, updated_at) VALUES (13,"OTOLARYNGOLOGY",now(),now())'
execute 'INSERT INTO specialties (id, name, created_at, updated_at) VALUES (43,"PAIN MANAGEMENT",now(),now())'
execute 'INSERT INTO specialties (id, name, created_at, updated_at) VALUES (49,"PATHOLOGY",now(),now())'
execute 'INSERT INTO specialties (id, name, created_at, updated_at) VALUES (19,"PEDIATRIC MEDICINE",now(),now())'
execute 'INSERT INTO specialties (id, name, created_at, updated_at) VALUES (70,"PERIPHERAL VASCULAR DISEASE",now(),now())'
execute 'INSERT INTO specialties (id, name, created_at, updated_at) VALUES (14,"PHYSICAL MEDICINE AND REHABILITATION",now(),now())'
execute 'INSERT INTO specialties (id, name, created_at, updated_at) VALUES (23,"PHYSICAL THERAPIST",now(),now())'
execute 'INSERT INTO specialties (id, name, created_at, updated_at) VALUES (58,"PHYSICIAN ASSISTANT",now(),now())'
execute 'INSERT INTO specialties (id, name, created_at, updated_at) VALUES (32,"PLASTIC AND RECONSTRUCTIVE SURGERY",now(),now())'
execute 'INSERT INTO specialties (id, name, created_at, updated_at) VALUES (7,"PODIATRY",now(),now())'
execute 'INSERT INTO specialties (id, name, created_at, updated_at) VALUES (72,"PREVENTATIVE MEDICINE",now(),now())'
execute 'INSERT INTO specialties (id, name, created_at, updated_at) VALUES (3,"PSYCHIATRY",now(),now())'
execute 'INSERT INTO specialties (id, name, created_at, updated_at) VALUES (30,"PULMONARY DISEASE",now(),now())'
execute 'INSERT INTO specialties (id, name, created_at, updated_at) VALUES (29,"RADIATION ONCOLOGY",now(),now())'
execute 'INSERT INTO specialties (id, name, created_at, updated_at) VALUES (35,"REGISTERED DIETITIAN OR NUTRITION PROFESSIONAL",now(),now())'
execute 'INSERT INTO specialties (id, name, created_at, updated_at) VALUES (53,"RHEUMATOLOGY",now(),now())'
execute 'INSERT INTO specialties (id, name, created_at, updated_at) VALUES (74,"SINGLE OR MULTISPECIALTY CLINIC OR GROUP PRACTICE",now(),now())'
execute 'INSERT INTO specialties (id, name, created_at, updated_at) VALUES (67,"SLEEP LABORATORY/MEDICINE",now(),now())'
execute 'INSERT INTO specialties (id, name, created_at, updated_at) VALUES (64,"SPEECH LANGUAGE PATHOLOGIST",now(),now())'
execute 'INSERT INTO specialties (id, name, created_at, updated_at) VALUES (68,"SPORTS MEDICINE",now(),now())'
execute 'INSERT INTO specialties (id, name, created_at, updated_at) VALUES (62,"SURGICAL ONCOLOGY",now(),now())'
execute 'INSERT INTO specialties (id, name, created_at, updated_at) VALUES (60,"THORACIC SURGERY",now(),now())'
execute 'INSERT INTO specialties (id, name, created_at, updated_at) VALUES (75,"UNDEFINED NON-PHYSICIAN TYPE (SPECIFY)",now(),now())'
execute 'INSERT INTO specialties (id, name, created_at, updated_at) VALUES (76,"UNDEFINED PHYSICIAN TYPE (SPECIFY)",now(),now())'
execute 'INSERT INTO specialties (id, name, created_at, updated_at) VALUES (21,"UROLOGY",now(),now())'
execute 'INSERT INTO specialties (id, name, created_at, updated_at) VALUES (57,"VASCULAR SURGERY",now(),now())'

  end

  def down
  end
end
