require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by the Rails when you ran the scaffold generator.

describe CostsController do

  def mock_cost(stubs={})
    @mock_cost ||= mock_model(Cost, stubs).as_null_object
  end

  describe "GET index" do
    it "assigns all costs as @costs" do
      Cost.stub(:all) { [mock_cost] }
      get :index
      assigns(:costs).should eq([mock_cost])
    end
  end

  describe "GET show" do
    it "assigns the requested cost as @cost" do
      Cost.stub(:find).with("37") { mock_cost }
      get :show, :id => "37"
      assigns(:cost).should be(mock_cost)
    end
  end

  describe "GET new" do
    it "assigns a new cost as @cost" do
      Cost.stub(:new) { mock_cost }
      get :new
      assigns(:cost).should be(mock_cost)
    end
  end

  describe "GET edit" do
    it "assigns the requested cost as @cost" do
      Cost.stub(:find).with("37") { mock_cost }
      get :edit, :id => "37"
      assigns(:cost).should be(mock_cost)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "assigns a newly created cost as @cost" do
        Cost.stub(:new).with({'these' => 'params'}) { mock_cost(:save => true) }
        post :create, :cost => {'these' => 'params'}
        assigns(:cost).should be(mock_cost)
      end

      it "redirects to the created cost" do
        Cost.stub(:new) { mock_cost(:save => true) }
        post :create, :cost => {}
        response.should redirect_to(cost_url(mock_cost))
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved cost as @cost" do
        Cost.stub(:new).with({'these' => 'params'}) { mock_cost(:save => false) }
        post :create, :cost => {'these' => 'params'}
        assigns(:cost).should be(mock_cost)
      end

      it "re-renders the 'new' template" do
        Cost.stub(:new) { mock_cost(:save => false) }
        post :create, :cost => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested cost" do
        Cost.stub(:find).with("37") { mock_cost }
        mock_cost.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => "37", :cost => {'these' => 'params'}
      end

      it "assigns the requested cost as @cost" do
        Cost.stub(:find) { mock_cost(:update_attributes => true) }
        put :update, :id => "1"
        assigns(:cost).should be(mock_cost)
      end

      it "redirects to the cost" do
        Cost.stub(:find) { mock_cost(:update_attributes => true) }
        put :update, :id => "1"
        response.should redirect_to(cost_url(mock_cost))
      end
    end

    describe "with invalid params" do
      it "assigns the cost as @cost" do
        Cost.stub(:find) { mock_cost(:update_attributes => false) }
        put :update, :id => "1"
        assigns(:cost).should be(mock_cost)
      end

      it "re-renders the 'edit' template" do
        Cost.stub(:find) { mock_cost(:update_attributes => false) }
        put :update, :id => "1"
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested cost" do
      Cost.stub(:find).with("37") { mock_cost }
      mock_cost.should_receive(:destroy)
      delete :destroy, :id => "37"
    end

    it "redirects to the costs list" do
      Cost.stub(:find) { mock_cost }
      delete :destroy, :id => "1"
      response.should redirect_to(costs_url)
    end
  end

end
