require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by the Rails when you ran the scaffold generator.

describe HospitalsController do

  def mock_hospital(stubs={})
    @mock_hospital ||= mock_model(Hospital, stubs).as_null_object
  end

  describe "GET index" do
    it "assigns all hospitals as @hospitals" do
      Hospital.stub(:all) { [mock_hospital] }
      get :index
      assigns(:hospitals).should eq([mock_hospital])
    end
  end

  describe "GET show" do
    it "assigns the requested hospital as @hospital" do
      Hospital.stub(:find).with("37") { mock_hospital }
      get :show, :id => "37"
      assigns(:hospital).should be(mock_hospital)
    end
  end

  describe "GET new" do
    it "assigns a new hospital as @hospital" do
      Hospital.stub(:new) { mock_hospital }
      get :new
      assigns(:hospital).should be(mock_hospital)
    end
  end

  describe "GET edit" do
    it "assigns the requested hospital as @hospital" do
      Hospital.stub(:find).with("37") { mock_hospital }
      get :edit, :id => "37"
      assigns(:hospital).should be(mock_hospital)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "assigns a newly created hospital as @hospital" do
        Hospital.stub(:new).with({'these' => 'params'}) { mock_hospital(:save => true) }
        post :create, :hospital => {'these' => 'params'}
        assigns(:hospital).should be(mock_hospital)
      end

      it "redirects to the created hospital" do
        Hospital.stub(:new) { mock_hospital(:save => true) }
        post :create, :hospital => {}
        response.should redirect_to(hospital_url(mock_hospital))
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved hospital as @hospital" do
        Hospital.stub(:new).with({'these' => 'params'}) { mock_hospital(:save => false) }
        post :create, :hospital => {'these' => 'params'}
        assigns(:hospital).should be(mock_hospital)
      end

      it "re-renders the 'new' template" do
        Hospital.stub(:new) { mock_hospital(:save => false) }
        post :create, :hospital => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested hospital" do
        Hospital.stub(:find).with("37") { mock_hospital }
        mock_hospital.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => "37", :hospital => {'these' => 'params'}
      end

      it "assigns the requested hospital as @hospital" do
        Hospital.stub(:find) { mock_hospital(:update_attributes => true) }
        put :update, :id => "1"
        assigns(:hospital).should be(mock_hospital)
      end

      it "redirects to the hospital" do
        Hospital.stub(:find) { mock_hospital(:update_attributes => true) }
        put :update, :id => "1"
        response.should redirect_to(hospital_url(mock_hospital))
      end
    end

    describe "with invalid params" do
      it "assigns the hospital as @hospital" do
        Hospital.stub(:find) { mock_hospital(:update_attributes => false) }
        put :update, :id => "1"
        assigns(:hospital).should be(mock_hospital)
      end

      it "re-renders the 'edit' template" do
        Hospital.stub(:find) { mock_hospital(:update_attributes => false) }
        put :update, :id => "1"
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested hospital" do
      Hospital.stub(:find).with("37") { mock_hospital }
      mock_hospital.should_receive(:destroy)
      delete :destroy, :id => "37"
    end

    it "redirects to the hospitals list" do
      Hospital.stub(:find) { mock_hospital }
      delete :destroy, :id => "1"
      response.should redirect_to(hospitals_url)
    end
  end

end
